FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["SoftManager.Presentation/SoftManager.Presentation.csproj", "SoftManager.Presentation/"]
RUN dotnet restore "SoftManager.Presentation/SoftManager.Presentation.csproj"
COPY . . 
WORKDIR "/src/SoftManager.Presentation"
RUN dotnet build "SoftManager.Presentation.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SoftManager.Presentation.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SoftManager.Web.dll"]
